core/urls.py
from django.urls import path

urlpatterns = [

]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('groups/',views.GroupsPage.as_view(),name='view_all_groups'),
    path('groups/<group>/',views.GroupPage.as_view(),name='group'),
    path('ban_user/<group>/<user_id>/',views.ban_user,name='ban_user'),
    path('groups/<group>/edit_group_cover/',views.edit_group_cover,name='edit_group_cover'),
    path('groups/<group>/subscription/',views.subscribe,name='subscribe'),
    path('<username>/groups/',views.UserCreatedGroupsPage.as_view(),name='user_created_groups'),
    path('create_group/',views.create_group, name='create_group'),
    path('groups/<username>/subscriptions/',views.UserSubscriptionList.as_view(),name='user_subscription_list'),
    path('group/result/',views.GroupSearch.as_view(), name='group_search'),
    path('banned_users/<group>/',views.banned_users,name='banned_users'),
    path('groups/category/<category_slug>/',views.list_of_group_by_category,name='list_of_group_by_category'),
]

juniorsproject/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('posts.urls')),
    path('messages/', include('messenger.urls')),
    path('', include('notifications.urls')),
    path('', include('reports.urls')),
    path('', include('groups.urls')),
    path('comment/', include('comments.urls')),
    path('', include('esearch.urls')),
    path('__debug__/', include(debug_toolbar.urls)),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('deactivate_post/<post>/',views.deactivate_post,name='deactivate_post'),
    path('edit_post/<post>/',views.edit_post,name='edit_post'),
    path('delete_post/<post>/',views.delete_post,name='delete_post'),
    # path('<post>/like/',views.like_post,name='like'),
    path('<group>/<post>/',views.post_detail,name='post_detail'),
    path('<slug>/like',views.PostLikeToggle,name='like-toggle'),
    path('api/<slug>/like',views.PostLikeAPIToggle.as_view(),name='like-api-toggle'),
    path('new_post/',views.new_post,name='new_post'),
    path('search/',views.SearchView.as_view(),name='search_results'),
    path('<post>/like/',views.like_subject,name='like'),
    path('trending/',views.TrendingPage.as_view(),name='trending'),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('show_reports/<group>/',views.show_reports,name='show_reports'),
    path('report_post/<post>/',views.report_post,name='report_post'),
    path('report_comment/<pk>/',views.report_comment,name='report_comment'),
    path('delete/<pk>/', views.delete_comment_report, name='delete_comment_report')
]

users/urls.py
from django.urls import path, reverse_lazy,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import (Signup, profile,
                   user_show_profile, FollowersPageView, FollowingPageView,
                   follow_user, all_message_requests, send_message_request,
                   accept_message_request, all_friends,UsersPageView,block_spammer
                   )
                   

app_name = 'users'

urlpatterns = [
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', login_required(auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'))), name='password_change'),
    path('password-change/done/', login_required(auth_views.PasswordChangeDoneView.as_view()), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('users:password_reset_complete')) , name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    path('profile/<int:id>', user_show_profile, name='profile_show_user'),
    path('following/', FollowingPageView.as_view(), name='view_all_following'),
    path('followers/', FollowersPageView.as_view(), name='view_all_followers'),
    path('follow_user/<user_id>', follow_user, name='follow_user' ),
    path('send_message_request/<user_id>',send_message_request, name='send_message_request'),
    path('accept_message_request/<user_id>', accept_message_request, name='accept_message_request'),
    path('friends/all/',all_friends, name='all_friends'),
    path('friends/requests/',all_message_requests, name='all_message_requests'),
    path('u/',UsersPageView.as_view(),name='view_all_users'),
    path('u/block_spammer/<user_id>/',block_spammer,name='block_spammer'),
    ]

groups/models.py
from django.db import models
from datetime import timedelta
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from slugify import UniqueSlugify

# Create your models here.

User = settings.AUTH_USER_MODEL

class GroupCategory(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('groups:list_of_group_by_category',args=[self.slug])

class Group(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=500)
    cover = models.ImageField(upload_to='group_covers/', blank=True, null=True)
    admins = models.ManyToManyField(User, related_name='inspected_groups')
    subscribers = models.ManyToManyField(User, related_name='subscribed_groups' ,blank=True)
    banned_users = models.ManyToManyField(User, related_name='forbidden_groups',blank=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(GroupCategory,on_delete=models.CASCADE)
    logo = models.ImageField(upload_to='group_logos/',blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = group_slugify(f"{self.title}")
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:group',
                       args=[self.slug])
    
    def get_admins(self):
        return self.admins.all()

    def get_picture(self):
        default_picture = settings.STATIC_URL + 'img/cover.png'
        if self.cover:
            return self.cover.url
        else:
            return default_picture

    def recent_posts(self):
        return self.submitted_posts.filter(created__gte=timezone.now() - timedelta(days=3)).count()

def group_unique_check(text, uids):
    if text in uids:
        return False
    return not Group.objects.filter(slug=text).exists()

group_slugify = UniqueSlugify(
                    unique_check=group_unique_check,
                    to_lower=True,
                    max_length=80,
                    separator='_',
                    capitalize=False
                )

groups/forms.py
from django import forms
from .models import Group

class GroupForm(forms.ModelForm):
    title = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder': 'Title'}))
    description = forms.CharField(label='',widget=forms.Textarea(attrs={'rows': 5,'placeholder':'Text'}))
    cover = forms.ImageField(label='Add Group Cover (optional)',widget=forms.FileInput(),help_text="Image dimensions should be <b>900 &#10005; 300</b>",required=False)
    class Meta:
        model = Group
        fields = ('title','description','cover','category')
        
class GroupCoverForm(forms.ModelForm):
    cover = forms.ImageField(label='Choose your group cover',widget=forms.FileInput(),help_text="Image dimensions should be <b>1200x250</b>",required=False)
    logo = forms.ImageField(label='Choose you group logo (will be cutted to round)',widget=forms.FileInput(),help_text="Image dimensions should be <b>72x72</b>",required=False)
    class Meta:
        model = Group
        fields = ('cover','logo')
        

groups/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Group
from posts.models import Post
from .decorators import user_is_group_admin,user_is_not_banned_from_group
from django.http import HttpResponse
from .forms import GroupForm,GroupCoverForm
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from users.models import CustomUser
from django.contrib.auth import get_user_model
from users.models import CustomUser
from django.http import JsonResponse
from django.db.models import Q
from groups.models import GroupCategory

# Create your views here.

User = settings.AUTH_USER_MODEL

class GroupsPage(ListView):
    model = Group
    queryset = Group.objects.all()
    paginate_by = 15
    template_name = 'groups/all_groups.html'
    context_object_name = 'groups'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = GroupCategory.objects.all()
        return context

class GroupPage(ListView):
    model = Post
    paginate_by = 20
    template_name = 'groups/group.html'
    context_object_name = 'posts'

    def get_queryset(self,**kwargs):
        self.group = get_object_or_404(Group,slug=self.kwargs['group'])
        return self.group.submitted_posts.filter(active=True)
    
    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context["bv"] = True
        context['admins'] = self.group.admins.all()
        context['group'] = self.group
        return context
    
class UserSubscriptionList(LoginRequiredMixin,ListView):
    model = Group
    paginate_by = 10
    template_name = 'groups/user_subscription_list.html'
    context_object_name = 'subscriptions'

    def get_queryset(self, **kwargs ):
        user = get_object_or_404(CustomUser,username=self.request.user.username)
        return user.subscribed_groups.all()

   



class UserSubscriptionListAjax(LoginRequiredMixin,ListView):
    model = Group
    paginate_by = 10
    template_name = 'sub_show_group.html'
    context_object_name = 'subscriptions_ajax'

    def get_context_data(self, **kwargs):          
        context = super().get_context_data(**kwargs)                     
        data =  get_object_or_404(CustomUser,username=self.request.user.username).subscribed_groups.all()
        context["data"] = data

        return  context



@login_required
@user_is_not_banned_from_group
def subscribe(request,group):
    group = get_object_or_404(Group,slug=group)
    user = request.user
    if group in user.subscribed_groups.all():
        group.subscribers.remove(user)
    else:
        group.subscribers.add(user)
    return HttpResponse(group.subscribers.count())

class UserCreatedGroupsPage(LoginRequiredMixin,ListView):
    model = Group
    paginate_by = 20
    template_name = 'groups/user_created_groups.html'
    context_object_name = 'user_groups'

    def get_queryset(self,**kwargs):
        user = get_object_or_404(CustomUser,username=self.request.user.username)
        return user.inspected_groups.all()

@login_required
def create_group(request):
    group_form = GroupForm()
    if request.method == 'POST':
        group_form = GroupForm(request.POST,request.FILES)
        if group_form.is_valid():
            new_group = group_form.save()
            new_group.admins.add(request.user)
            new_group.subscribers.add(request.user)
            return redirect(new_group.get_absolute_url())
    else:
        group_form = GroupForm()
    return render(request,'groups/create_group.html',{'group_form':group_form})

@login_required
@user_is_group_admin
def edit_group_cover(request,group):
    group = get_object_or_404(Group,slug=group)
    if request.method == 'POST':
        group_form = GroupCoverForm(instance=group,data=request.POST,files=request.FILES)
        if group_form.is_valid():
            group_form.save()
            return redirect(group.get_absolute_url())
        else:
            group_form = GroupCoverForm()
    else:
        group_form = GroupCoverForm()
    return render(request,'groups/edit_group_cover.html',{'group_form':group_form})

@login_required
@user_is_group_admin
def banned_users(request,group):
    group = get_object_or_404(Group, slug=group)
    users = group.banned_users.all()
    paginator = Paginator(users, 20)
    page = request.GET.get('page')
    if paginator.num_pages > 1:
        p = True
    else:
        p = False
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    p_obj = users
    bv = True
    return render(request, 'groups/banned_users.html', {
        'group':group,
        'bv':bv,
        'page':page,
        'p_obj':p_obj,
        'p':p,
        'users':users
    })

@login_required
@user_is_group_admin
def ban_user(request,group,user_id):
    group = get_object_or_404(Group,slug=group)
    user = get_object_or_404(CustomUser,id=user_id)
    print(" first group {0}, user{1}  ".format(group, user))

    if group in user.subscribed_groups.all():
        group.subscribers.remove(user)
        group.banned_users.add(user)
        return redirect('groups:banned_users',group=group.slug)
    else:
        group.banned_users.remove(user)
        return redirect('groups:banned_users',group=group.slug)

class GroupSearch(ListView):
    model = Group 
    template_name = 'groups/group_search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('group_search')
        object_list = Group.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
        return object_list

def list_of_group_by_category(request,category_slug):
    categories = GroupCategory.objects.all()
    group = Group.objects.all()
    if category_slug:
        category = get_object_or_404(GroupCategory,slug=category_slug)
        group = group.filter(category=category)
    template = 'groups/list_of_group_by_category.html'
    context = {'categories':categories,'group':group,'category':category}
    return render(request,template,context)
    

groups/templates/groups/group.html
{% extends 'base.html' %}

{% load static %}

{% load humanize %}

{% block title %}Home{% endblock title %}

{% block content %}

<!-- <style>
  body{
    background-image:url("/static/img/default_background.jpeg");
    background-size: 100%;
  }
</style> -->

<!-- Page Content -->

    <div class="row">
      {% if group.cover %}
      <img class="mb-3" style="width: 1200px;height: 250px;" src="{{ group.cover.url }}" alt="">
      {% else %}
      <img class="mb-3" src="{% static 'img/default_cover.jpeg' %}" style="width: 1200px;height: 250px;" alt="">
      {% endif %}
      <!-- Blog Entries Column -->
      <div class="col-md-8">

        {% for post in posts %}
        <!-- Blog Post -->
        <div class="card mb-4">
          {% if post.image %}
          <div class="text-center">
          <img class="card-img-top" src="{{ post.image.url }}">
          </div>
          {% endif %}
          <div class="card-body">
            <h2 class="card-title">{{ post.title }}</h2>
            <p class="card-text">{{ post.body|truncatewords_html:50|urlize }}</p>
            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
            {% if post in user.liked_posts.all %}
              <a href="{% url 'posts:like' post.slug %}" class="btn btn-primary float-right"><i class="fas fa-thumbs-down"></i></a>
            {% else %}
              <a href="{% url 'posts:like' post.slug %}" class="btn btn-primary float-right"><i class="fas fa-thumbs-up"></i></a>
            {% endif %}
          </div>
          <div class="card-footer text-muted">
            Posted on {{ post.created|naturaltime }} by
            <a href="{% url 'users:profile_show_user' user.id %}">{{ post.author.profile.screen_name }}</a>
            <p class="float-right">{{ post.comments.count }} Comments</p>
          </div>
        </div>
        {% endfor %}

  


        <!-- Pagination -->
        <nav>   
          <ul class="pagination justify-content-center mt-2">
           {% if is_paginated %}
            {% if page_obj.has_previous %}
              <li class="page-item">
                  <a href="?page={{ page_obj.previous_page_number }}"  tabindex="-1" aria-disabled="true" class="page-link">Previous</a>
              </li>
            {% else %}
              <li class="page-item disabled"><a class="page-link">Previous</a></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="page-item active"  aria-current="page">
                    <a class="page-link">
                        {{ i }}
                         <span class="sr-only">(current)</span>
                    </a>
              </li>
              {% else %}
                <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item page-link"><a href="?page={{ page_obj.next_page_number }}" >Next</a></li>
            {% else %}
              <li class="disabled page-item"><a class="page-link">Next</a></li>
            {% endif %}
        {% endif %}
      </ul>
      </nav>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Side Widget -->
        <div class="ml-4">
        <div class="card ml-5" style="width: 18rem;">
          <div class="card-body">
            {% if group.logo %}
            <img class="mb-3" src="{{ group.logo.url }}" style="width:75px;height:75px;display:block;margin-left:auto;margin-right:auto;border-radius:50%;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
            {% else %}
              {% if group.category.name == 'Gaming' %}
                <img class="mb-3" src="{% static 'img/gaming.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Health & Fitness' %}
                <img class="mb-3" src="{% static 'img/fitness.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'News' %}
                <img class="mb-3" src="{% static 'img/news.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Sports' %}
                <img class="mb-3" src="{% static 'img/sports.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Tv' %}
                <img class="mb-3" src="{% static 'img/tv.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif post.group.category.name == 'Tech' %}
                <img class="mb-3" src="{% static 'img/tech.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Music' %}
                <img class="mb-3" src="{% static 'img/music.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Movies' %}
                <img class="mb-3" src="{% static 'img/movies.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Food' %}
                <img class="mb-3" src="{% static 'img/food.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Shopping' %}
                <img class="mb-3" src="{% static 'img/shopping.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Travelling' %}
                <img class="mb-3" src="{% static 'img/travelling.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Tech' %}
                <img class="mb-3" src="{% static 'img/tech.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% elif group.category.name == 'Science' %}
                <img class="mb-3" src="{% static 'img/science.png' %}" style="width:75px;height:75px;display: block;margin-left: auto;margin-right: auto;" alt=""><h5 class="card-title text-center" style="color:cadetblue;">About Community</h5>
              {% endif %}
            {% endif %}
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Title: <b>{{ group.title }}</b><span class="badge badge-primary float-right">{{ group.category.name }}</span></li>
            <li class="list-group-item">Description: {{ group.description|truncatewords_html:50|urlize }} </li>
            <li class="list-group-item">Total Posts: <span class="badge badge-primary">{{ group.submitted_posts.count }}</span></li>
            <li class="list-group-item">Admins:
              {% for admin in group.get_admins %}
                      <a href="{% url 'users:profile_show_user' user.id %}">{{ admin.profile.screen_name }}</a></p>
              {% endfor %}
            </li>
            <li class="list-group-item">Subscribers: <span class="badge badge-primary">{{ group.subscribers.count }}</span></li>
          </ul>
          <div class="card-body">
            {% if user in group.banned_users.all %}
              <a class="btn btn-secondary float-right mr-2">Banned</a>
            {% else %}
              {% if group in request.user.subscribed_groups.all %}
              <a href="{% url 'groups:subscribe' group.slug %}" class="btn btn-secondary float-right mr-2" id="subscribe_group">Unsubscribe</a>
              {% else %}
              <a href="{% url 'groups:subscribe' group.slug %}" class="btn btn-primary float-right" id="subscribe_group">Subscribe</a>
              {% endif %}
            {% endif %}
            <p class="text-muted">Created {{ group.created|date }}</p>
            {% if admins %}
            {% if request.user in admins %}
            <a href="{% url 'groups:edit_group_cover' group.slug %}" class="float-right">Edit group cover</a>
            <a href="{% url 'reports:show_reports' group.slug %}">View reports</a>
            <a href="{% url 'groups:banned_users' group.slug %}">Banned users</a>
            {% endif %}
            {% endif %}
          </div>
        </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  <!-- /.container -->

  <script type="text/javascript">
    $(document).ready(function(){
      $("a#subscribe_group").on("click", function () {
        {% if not request.user.is_authenticated %}
        window.location.href = "{% url 'users:login' %}";
        {% else %}
        var $msg=$(this);
        var $subscribe_url=$(this).attr("href");
        var $group_subscribers=$('span#group_subscribers')
        $.ajax({
          url: $subscribe_url,
          type: 'GET',
          success: function (data) {
            if ($msg.text() == 'Subscribe') {
              $msg.removeClass('btn-primary');
              $msg.addClass('btn-secondary');
              $msg.text('Unsubscribe');
              $board_subscribers.text(data);
            } else if ($msg.text() == 'Unsubscribe') {
              $msg.removeClass('btn-secondary');
              $msg.addClass('btn-primary');
              $msg.text('Subscribe');
              $group_subscribers.text(data);
            } else { console.log('Unexpected error!'); }
          }
        });
        {% endif %}
        return false;
      });
    });
    </script>
    
{% endblock content %}

groups/templates/groups/list_of_group_by_category.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}{{ category.name }} category{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
    <div class="col-md-8">
    <h2 class="text-center pb-3" style="color:cadetblue;">{{ category.name }}</h2>
    <div class="list-group">
      {% for groups in group %}
      <ul class="list-group">
        <li class="list-group-item">
          Title: <a href="{{ groups.get_absolute_url }}" class="name">{{ groups.title }}</a><br>
          {% if groups in request.user.subscribed_groups.all %}
          <a href="{% url 'groups:subscribe' groups.slug %}" class="btn btn-secondary btn-xs float-right" id="subscribe_group">Unsubscribe</a>
          {% else %}
          <a href="{% url 'groups:subscribe' groups.slug %}" class="btn btn-primary btn-xs float-right" id="subscribe_group">Subscribe</a>
          {% endif %}
          <span class="name">Created: {{ groups.created|naturaltime }}</span><br>
          <span class="name">{{ groups.subscribers.count }} subscribers</span>
        </li>
      </ul>
        {% empty %}
        <div class="card p-4 my-4 mx-0">
          <h6 class="text-center">No Groups Found</h6>
          <div style="margin:0 auto;">
          <p class="text-muted">There are no groups created yet.</p>
          </div>
        </div>
        {% endfor %}
      </div>
      </div>
    
    <div class="col-md-4">
      <!-- Search Widget -->
      <div class="card">
        <div class="list-group">
          <button type="button" class="list-group-item list-group-item-action disabled text-center" style="color:cadetblue;">
            Categories
          </button>
          <a href="{% url 'groups:view_all_groups' %}" class="list-group-item list-group-item-action">All groups</a>
          {% for category in categories %}
          <a href="{{ category.get_absolute_url }}" class="list-group-item list-group-item-action">{{ category.name }}</a>
          {% endfor %}
        </div>
      </div>
    </div>
    </div>
    </div>
    
    <script type="text/javascript">
    $(document).ready(function(){
      $("a#subscribe_group").on("click", function () {
        {% if not request.user.is_authenticated %}
        window.location.href = "{% url 'users:login' %}";
        {% else %}
        var $msg = $(this);
        var $subscribe_url = $(this).attr("href");
        var $group_subscribers = $('span#group_subscribers')
        $.ajax({
          url: $subscribe_url,
          type: 'GET',
          success: function (data) {
            if ($msg.text() == 'Subscribe') {
              $msg.removeClass('btn-primary');
              $msg.addClass('btn-secondary');
              $msg.text('Unsubscribe');
              $group_subscribers.text(data + ' readers');
            }
            else if ($msg.text() == 'Unsubscribe') {
              $msg.removeClass('btn-secondary');
              $msg.addClass('btn-primary');
              $msg.text('Subscribe');
              $group_subscribers.text(data + ' readers');
            }
            else {
              console.log('Unexpected error!');
            }
          }
        });
        {% endif %}
        return false;
      });
    });
    </script>
{% endblock content %}

groups/templates/groups/sub_show_group.html
{% for co in context  %}
{{co.title}}
{% endfor %}