comments/urls.py
from django.urls import path
from .views import delete_comment,deactivate_comment

app_name = 'comments'

urlpatterns = [
    path('delete_comment/<int:pk>/',delete_comment, name='delete_comment'),
    path('deactivate_comment/<pk>/',deactivate_comment,name='deactivate_comment'),
]

core/urls.py
from django.urls import path

urlpatterns = [

]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('groups/',views.GroupsPage.as_view(),name='view_all_groups'),
    path('groups/<group>/',views.GroupPage.as_view(),name='group'),
    path('ban_user/<group>/<user_id>/',views.ban_user,name='ban_user'),
    path('groups/<group>/edit_group_cover/',views.edit_group_cover,name='edit_group_cover'),
    path('groups/<group>/subscription/',views.subscribe,name='subscribe'),
    path('<username>/groups/',views.UserCreatedGroupsPage.as_view(),name='user_created_groups'),
    path('create_group/',views.create_group, name='create_group'),
    path('groups/<username>/subscriptions/',views.UserSubscriptionList.as_view(),name='user_subscription_list'),
    path('group/result/',views.GroupSearch.as_view(), name='group_search'),
    path('banned_users/<group>/',views.banned_users,name='banned_users'),
    path('groups/category/<category_slug>/',views.list_of_group_by_category,name='list_of_group_by_category'),
]

juniorsproject/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('posts.urls')),
    path('messages/', include('messenger.urls')),
    path('', include('notifications.urls')),
    path('', include('reports.urls')),
    path('', include('groups.urls')),
    path('comment/', include('comments.urls')),
    path('', include('esearch.urls')),
    path('__debug__/', include(debug_toolbar.urls)),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('deactivate_post/<post>/',views.deactivate_post,name='deactivate_post'),
    path('edit_post/<post>/',views.edit_post,name='edit_post'),
    path('delete_post/<post>/',views.delete_post,name='delete_post'),
    # path('<post>/like/',views.like_post,name='like'),
    path('<group>/<post>/',views.post_detail,name='post_detail'),
    path('<slug>/like',views.PostLikeToggle,name='like-toggle'),
    path('api/<slug>/like',views.PostLikeAPIToggle.as_view(),name='like-api-toggle'),
    path('new_post/',views.new_post,name='new_post'),
    path('search/',views.SearchView.as_view(),name='search_results'),
    path('<post>/like/',views.like_subject,name='like'),
    path('trending/',views.TrendingPage.as_view(),name='trending'),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('show_reports/<group>/',views.show_reports,name='show_reports'),
    path('report_post/<post>/',views.report_post,name='report_post'),
    path('report_comment/<pk>/',views.report_comment,name='report_comment'),
    path('delete/<pk>/', views.delete_comment_report, name='delete_comment_report')
]

users/urls.py
from django.urls import path, reverse_lazy,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import (Signup, profile,
                   user_show_profile, FollowersPageView, FollowingPageView,
                   follow_user, all_message_requests, send_message_request,
                   accept_message_request, all_friends,UsersPageView,block_spammer
                   )
                   

app_name = 'users'

urlpatterns = [
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', login_required(auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'))), name='password_change'),
    path('password-change/done/', login_required(auth_views.PasswordChangeDoneView.as_view()), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('users:password_reset_complete')) , name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    path('profile/<int:id>', user_show_profile, name='profile_show_user'),
    path('following/', FollowingPageView.as_view(), name='view_all_following'),
    path('followers/', FollowersPageView.as_view(), name='view_all_followers'),
    path('follow_user/<user_id>', follow_user, name='follow_user' ),
    path('send_message_request/<user_id>',send_message_request, name='send_message_request'),
    path('accept_message_request/<user_id>', accept_message_request, name='accept_message_request'),
    path('friends/all/',all_friends, name='all_friends'),
    path('friends/requests/',all_message_requests, name='all_message_requests'),
    path('u/',UsersPageView.as_view(),name='view_all_users'),
    path('u/block_spammer/<user_id>/',block_spammer,name='block_spammer'),
    ]

reports/models.py
from django.db import models
from django.conf import settings
from groups.models import Group
from comments.models import Comment
from posts.models import Post

# Create your models here.

User = settings.AUTH_USER_MODEL

class Report(models.Model):
    reporter = models.ForeignKey(User,related_name='reported',null=True,on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment,related_name='comment_reports',blank=True,null=True,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,related_name='post_reports',blank=True,null=True,on_delete=models.CASCADE)
    group = models.ForeignKey(Group,related_name='group_reports',blank=True,null=True,on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        if self.comment:
            return '{} reported a comment {}.'.format(
                self.reporter.profile.screen_name(),self.comment.body
            )
        else:
            return '{} reported a post entitled \"{}\" posted by \"{}\".'.format(
                self.reporter.profile.screen_name(),
                self.post, self.post.author
            )

    @staticmethod
    def get_reports(groups_slug=None):
        if groups_slug:
            reports = Report.objects.filter(active=True,
                                            group__slug__icontains=groups_slug)
        else:
            reports = Report.objects.filter(active=True)
        return reports

reports/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from groups.models import Group
from comments.models import Comment
from posts.models import Post
from juniorsproject.decorators import ajax_required
from .models import Report
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

@login_required
@ajax_required
def report_post(request,post):
    post = get_object_or_404(Post,slug=post)
    group = post.group
    rep = request.user
    Report.objects.create(reporter=rep,
                          post=post,
                          group=group)
    return HttpResponse('Report has been sent to admins')

@login_required
@ajax_required
def report_comment(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    rep = request.user
    group = comment.post.group
    Report.objects.create(reporter=rep,
                          comment=comment,
                          group=group)
    return redirect('posts:post_detail',group=group.slug,post=comment.post.slug)


@login_required
@ajax_required
def delete_comment_report(request, pk):
    comment = get_object_or_404(Comment,pk=pk)
    report_comment =  get_object_or_404(Report, comment=comment)
    comment.delete()
    report_comment.delete()
    return HttpResponse("Hello world")


@login_required
def show_reports(request,group):
    group = get_object_or_404(Group,slug=group)
    admins = group.admins.all()
    if request.user in admins:
        reports = group.group_reports.filter(active=True)
        bv = True
        page = request.GET.get('page', 1)
        paginator = Paginator(reports,10)
        try:
            reports = paginator.page(page)
        except PageNotAnInteger:
            reports = paginator.page(1)
        except EmptyPage:
            reports = paginator.page(paginator.num_pages)
        return render(request,'reports/show_reports.html',{
            'reports':reports,
            'group':group,
            'bv':bv,
            'admins':admins
        })
        

reports/templates/reports/show_reports.html
{% extends 'base.html' %}

{% load groups_tags %}

{% load humanize %}

{% block title %}Reports{% endblock title %}

{% block content %}
<p class="text-muted text-center">
    Keep your group safe and fun.<br/>
    Delete / Ban unwanted Posts & Comments / Authors & Commenters from the group.
  </p>
  {% for report in reports %}
  <div class="card mb-2" style="border:none; border-bottom:1px solid #dcd7d7;">
    <div class="card-body p-4">
      {% if report.post %}
        <h6>
          <a href="{{ report.post.get_absolute_url }}">{{report}}</a>
        </h6>
        <br>
        <a href="{% url 'posts:deactivate_post' report.post.slug %}" class="btn btn-outline-primary btn-sm">Delete</a>
        <a href="{% url 'groups:ban_user' report.post.group.slug report.post.author.id %}" class="btn btn-outline-danger btn-sm">Ban Author</a>
      {% else %}
        <h6>
          <a href="{{ report.comment.post.get_absolute_url }}">{{report}}</a>
        </h6>
        <br>
        <a href="{% url 'comments:deactivate_comment' report.comment.id %}" class="btn btn-outline-primary btn-sm">Delete</a>
        <a href="{% url 'groups:ban_user' report.comment.post.group.slug report.comment.commenter.id %}" class="btn btn-outline-danger btn-sm">Ban Commenter</a>
        {% url 'groups:ban_user' report.comment.post.group.slug report.comment.commenter.id %}
      {% endif %}
      <div style="float:right;">
        <p class="text-muted">
          Reported <span>{{report.created|naturaltime}}</span> by <a href="{% url 'users:profile_show_user' report.reporter.id %}">{{report.reporter.profile.screen_name}}</a>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}

<nav aria-label="Page navigation example">
  {% if reports.has_other_pages %}
  <ul class="pagination justify-content-center pt-5 pb-5">
    {% if reports.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ reports.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in reports.paginator.page_range %}
    {% if reports.number == i %}
    <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if reports.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ reports.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  {% endif %}
</nav>
{% endblock content %}