core/urls.py
from django.urls import path

urlpatterns = [

]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('groups/',views.GroupsPage.as_view(),name='view_all_groups'),
    path('groups/<group>/',views.GroupPage.as_view(),name='group'),
    path('ban_user/<group>/<user_id>/',views.ban_user,name='ban_user'),
    path('groups/<group>/edit_group_cover/',views.edit_group_cover,name='edit_group_cover'),
    path('groups/<group>/subscription/',views.subscribe,name='subscribe'),
    path('<username>/groups/',views.UserCreatedGroupsPage.as_view(),name='user_created_groups'),
    path('create_group/',views.create_group, name='create_group'),
    path('groups/<username>/subscriptions/',views.UserSubscriptionList.as_view(),name='user_subscription_list'),
    path('group/result/',views.GroupSearch.as_view(), name='group_search'),
    path('banned_users/<group>/',views.banned_users,name='banned_users'),
    path('groups/category/<category_slug>/',views.list_of_group_by_category,name='list_of_group_by_category'),
]

juniorsproject/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('posts.urls')),
    path('messages/', include('messenger.urls')),
    path('', include('notifications.urls')),
    path('', include('reports.urls')),
    path('', include('groups.urls')),
    path('comment/', include('comments.urls')),
    path('', include('esearch.urls')),
    path('__debug__/', include(debug_toolbar.urls)),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

messenger/urls.py
from django.urls import path
from . import views

app_name = 'messenger'

urlpatterns = [
    path('check/',views.check,name='check_message'),
    path('send/',views.send,name='send_message'),
    path('u/<username>/',views.messages,name='messages'),
    path('',views.inbox,name='inbox'),
    path('delete/',views.delete,name='delete_message'),
    path('load_new_messages/',views.load_new_messages,name='load_new_messages'),
    path('load_last_twenty_messages/',views.load_last_twenty_messages,name='load_last_twenty_messages'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('deactivate_post/<post>/',views.deactivate_post,name='deactivate_post'),
    path('edit_post/<post>/',views.edit_post,name='edit_post'),
    path('delete_post/<post>/',views.delete_post,name='delete_post'),
    # path('<post>/like/',views.like_post,name='like'),
    path('<group>/<post>/',views.post_detail,name='post_detail'),
    path('<slug>/like',views.PostLikeToggle,name='like-toggle'),
    path('api/<slug>/like',views.PostLikeAPIToggle.as_view(),name='like-api-toggle'),
    path('new_post/',views.new_post,name='new_post'),
    path('search/',views.SearchView.as_view(),name='search_results'),
    path('<post>/like/',views.like_subject,name='like'),
    path('trending/',views.TrendingPage.as_view(),name='trending'),
]

users/urls.py
from django.urls import path, reverse_lazy,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import (Signup, profile,
                   user_show_profile, FollowersPageView, FollowingPageView,
                   follow_user, all_message_requests, send_message_request,
                   accept_message_request, all_friends,UsersPageView,block_spammer
                   )
                   

app_name = 'users'

urlpatterns = [
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', login_required(auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'))), name='password_change'),
    path('password-change/done/', login_required(auth_views.PasswordChangeDoneView.as_view()), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('users:password_reset_complete')) , name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    path('profile/<int:id>', user_show_profile, name='profile_show_user'),
    path('following/', FollowingPageView.as_view(), name='view_all_following'),
    path('followers/', FollowersPageView.as_view(), name='view_all_followers'),
    path('follow_user/<user_id>', follow_user, name='follow_user' ),
    path('send_message_request/<user_id>',send_message_request, name='send_message_request'),
    path('accept_message_request/<user_id>', accept_message_request, name='accept_message_request'),
    path('friends/all/',all_friends, name='all_friends'),
    path('friends/requests/',all_message_requests, name='all_message_requests'),
    path('u/',UsersPageView.as_view(),name='view_all_users'),
    path('u/block_spammer/<user_id>/',block_spammer,name='block_spammer'),
    ]

templates/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "css.html" %}
    {% include "js.html" %}
    <title>{% block title %}{% endblock title %}</title>    
    {% block head %}
    {% endblock head %}
</head>
<body style="background-color: #f1f1f1;">
    {% include "navbar.html" %}
    <div class="container " style="min-height: 100%;   margin-bottom:50%; ">
        {% block content %}
        {% endblock content %}
    </div>
    <button onclick="topFunction()" id="myBtn" title="Go to top">BACK TO TOP</button>
    <style>
      #myBtn {
  display: none; /* Hidden by default */
  position: fixed; /* Fixed/sticky position */
  bottom: 20px; /* Place the button at the bottom of the page */
  right: 30px; /* Place the button 30px from the right */
  z-index: 99; /* Make sure it does not overlap */
  border: none; /* Remove borders */
  outline: none; /* Remove outline */
  background-color: cadetblue; /* Set a background color */
  color: white; /* Text color */
  cursor: pointer; /* Add a mouse pointer on hover */
  padding: 15px; /* Some padding */
  border-radius: 10px; /* Rounded corners */
  font-size: 18px; /* Increase font size */
}
#myBtn:hover {
  background-color: #555; /* Add a dark-grey background on hover */
}
    </style>

    <script>
      //Get the button:
mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}
    </script>

  <script>
      $(".like-btn").click(function(e){
        e.preventDefault()
        var this_ = $(this)
        var likeUrl = this_.attr("data-href")
        var likeCount = parseInt(this_.attr("data-likes")) 
           $.ajax({
            url: likeUrl,
            method: "GET",
            success: function(data){
              if(data.liked == true){
                console.log( data.liked );
                document.getElementById('btn_like').innerHTML = '<i class="fas fa-thumbs-up fa-lg"></i>';
                likeCount = likeCount + 1
                document.getElementById('btn_like_all').innerHTML = likeCount + " Likes";
                if(likeCount == -1){likeCount +=1}
                console.log(0);
              }else{
                console.log( data.liked );
                document.getElementById('btn_like').innerHTML = '<i class="far fa-thumbs-up fa-lg"></i>';
                likeCount = likeCount - 1
                if(likeCount == -1){likeCount +=1}
                console.log(0);
                document.getElementById('btn_like_all').innerHTML = likeCount +  " Likes";

              }

            }, error: function(error){
              console.log(error)
              console.log("error")
            }
          });
       
      
  })
   
   </script>
</body>
</html>

templates/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<link rel="stylesheet" href="{% static 'css/custom.css' %}">

templates/footer.html
<div class="card">
    <footer id="sticky-footer" class="py-4 card-body" style="background-color: #3b4249; color: #b7b7b7; ">
      <div class="container text-center">
        <small>Copyright &copy; Juniors</small>
      </div>
    </footer>

</div>

templates/home.html
{% extends "base.html" %}

{% block content %}


<div class="row">
    <div class="col-8 ">
        <div class="col-10 pb-3">
            <div class="card">
                <h6 class="card-header bg-white border-bottom-0">
                    <a href="#" class="mr-2 card-link">Group name</a>
                        <small class="text-right ">
                            Posted by <a href="#">user</a>
                        </small>
                        <small>12 hours ago</small>
                </h6>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                </div>
            
                <div class="card-header">
                    <div class="card-text pl-3">
                        <a href="#" class="mr-2 card-link"><i class="fas fa-comments"></i> 4.4k Comments</a>
                        <a href="#" class="mr-2 card-link"><i class="fas fa-share"></i> Share</a>
                        <a href="#" class="mr-2 card-link"><i class="fas fa-save"></i> Save</a>
                    </div>
                </div>
        
        </div>
        </div>
        <div class="col-10 pb-3">
            <div class="card">
                <h6 class="card-header bg-white border-bottom-0">
                    <a href="#" class="mr-2 card-link text-link" >Group name</a>
                        <small class="text-right ">
                            Posted by <a href="#">user</a>
                        </small>
                        <small>12 hours ago</small>
                </h6>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                </div>
            
                <div  class="card-header">
                    <div class="card-text pl-3">
                        <a href="#" class="mr-2 card-link"><i class="fas fa-comments"></i> 4.4k Comments</a>
                        <a href="#" class="mr-2 card-link"><i class="fas fa-share"></i> Share</a>
                        <a href="#" class="mr-2 card-link"><i class="fas fa-save"></i> Save</a>
                    </div>
                </div>
                </div>
        </div>
        <div class="col-10 pb-3">
            <div class="card">
                <h6 class="card-header bg-white border-bottom-0">
                    <a href="#" class="mr-2 card-link text-link" >Group name</a>
                        <small class="text-right ">
                            Posted by <a href="#">user</a>
                        </small>
                        <small>12 hours ago</small>
                </h6>
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                </div>
            
                <div  class="card-header">
                    <div class="card-text pl-3">
                        <a href="#" class="mr-2 card-link"><i class="fas fa-comments"></i> 4.4k Comments</a>
                        <a href="#" class="mr-2 card-link"><i class="fas fa-share"></i> Share</a>
                        <a href="#" class="mr-2 card-link"><i class="fas fa-save"></i> Save</a>
                    </div>
                </div>
                </div>
        </div>
    </div>
    <div class="col-4">
        <div class="col-12 pb-5">
            <div class="card">
                <div class="card-header text-center">Top languages are used</div>
                <div class="card-body text-center">
                    <a href="#" class="card-link">Python</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="card-link">Javascript</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="card-link">TypeScript</a>
                </div>
            </div>
        </div>
        <div class="col-12 pb-5">
            <div class="card">
                <div class="card-header text-center">Top technologies are used</div>
                <div class="card-body text-center">
                    <a href="#" class="card-link">Docker</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="card-link">Angular</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="card-link">React</a>

                </div>
            </div>
        </div>
        <div class="col-12 pb-5">
            {% include "footer.html" %}
        </div>
    
    </div>
</div>



{% endblock content %}

templates/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% if request.user.is_authenticated %}
  <script src="{% static 'js/core_func.js' %}"></script>
  <script src="{% static 'js/check_messages.js' %}"></script>
{% endif %}

templates/navbar.html
{% load static %}

<style> 
  .dropdown-toggle::after { 
            margin-left: 6px;
        } 
        body .btn {
  outline: 0 !important;
}
.btn.active.focus,
.btn.active:focus,
.btn.focus,
.btn.focus:active,
.btn:active:focus,
.btn:focus {
  outline: 0 !important;
  outline-offset: 0  !important;
  background-image: none  !important;
  -webkit-box-shadow: none !important;
  box-shadow: none  !important;
}
.user-dropdown{
  top: 53px;
}
.dropdown-group{
  left: -40px;
}
.user-dropdown:after {
    content:"";
    position: absolute;
    right: 20px;
    top: -10px;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 0 10px 10px 10px;
    border-color: transparent transparent #eeeeee transparent;
    z-index:9998;
}

.drop-group-custom{
  width: 250px;
}

</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm p-3 mb-5 bg-white rounded" style="height: 70px;">
    <a class="navbar-brand" href="{% url 'posts:home' %}"><img src="{% static 'img/logo.jpeg' %}" width="156" height="32" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item typewriter" >
            <b class="nav-link" style="  color: #007BFF;"> Junior + Junior = Senior</b>     
        </li>
        <li class="nav-item">
          <div class="dropdown mr-3 ml-3 ">
            <button class="btn btn-outline-primary dropdown-toggle pr-4 pl-4 dropdown-toggle"  id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offest='10,20'>
                Groups
            </button>
            <form action="{% url 'groups:group_search' %}" method="GET">
              <div class="dropdown-menu custom-menu p-3 dropdown-group drop-group-custom" aria-labelledby="dropdownMenu2">
                <input type="text" class="form-control" name="group_search" placeholder="Search for groups">
                {% if groups %}
                <li class="mt-2 mb-2" style="color:cadetblue;"><small>MY GROUPS</small></li>
                  {% for group in groups %}
                    {% if user in group.subscribers.all %}
                      <a href="{{ group.get_absolute_url }}" class="list-group-item text-muted">{{ group.title }}</a>
                    {% endif %}
                  {% endfor %}
                {% endif %}
              </div>
            </form>
          </div>
        </li>
        <li>
            <form method="get" class="input-group my-2 my-lg-0" action="{% url 'posts:search_results' %}">
                <input type="search" class="form-control" placeholder="Search for posts" aria-label="Search" name="title">
                <div class="input-group-append" id="button-addon4">
                  <button class="btn btn-outline-secondary" type="sumbit"><i class="fas fa-search"></i></button>
                </div>
            </form>
        </li>   
      </ul>
      {% if user.is_authenticated %}
      <a href="{% url 'posts:trending' %}" class="nav-link link" style="color:#e25822" title="Trending"><i class="fas fa-fire fa-lg"></i></a>
      <a href="{% url 'posts:new_post' %}" class="nav-link link" title="Create Post"><i  class="fas fa-pen"></i></a> 
      <a href="{% url 'notifications:activities' %}" id="check_activities" class="nav-link link" title="Notifications"><i class="fas fa-bell"></i><small><span class="badge badge-pill badge-danger" style="vertical-align: top;" id="activities_count"></span></small></a>
      <a href="{% url 'messenger:inbox' %}" id="check_messages" class="nav-link link"><i class="fas fa-inbox"></i><small><span class="badge badge-pill badge-danger" style="vertical-align: top;" id="messages_count"></span></small></a>
      <ul class="navbar-nav">
        <li>
          <div class="dropdown mr-3 ml-3 ">
              <button class="btn btn-outline-secondary dropdown-toggle"  id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offest='10,20' style="width: 170px;">
                <img src="{{ user.profile.get_picture }}" width="30px" height="30px" class="rounded mr-2 ml-2" alt="">
                {{user.username}}
              </button>
              <div class="dropdown-menu dropdown-menu-right user-dropdown" aria-labelledby="dropdownMenu2" style="border-radius: 0; margin-top: -1px;">
                <a class="dropdown-item" href="{% url 'users:profile' %}">
                  <i class="fas fa-user-alt fa-sm pr-2"></i> 
                    My Profile
                </a>
              <a class="dropdown-item" href="{% url 'groups:user_created_groups' request.user.username %}"><i class="fas fa-users"></i> My Groups</a>
              <a href="{% url 'groups:create_group' %}" class="dropdown-item" title="Create Group"><small>New group</a>
              <a class="dropdown-item" href="{% url 'groups:user_subscription_list' request.user.username %}">Subscriptions</a>
              <a class="dropdown-item" href="{% url 'users:all_friends'%}">All Friends</a>              
              <a class="dropdown-item" href="{% url 'users:all_message_requests'%}">Requests</a>              
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'users:logout' %}" >
                  <i class="fas fa-sign-out-alt fa-sm pr-2"></i>  
                  Logout
                </a>
              </div>
            </div>
        </li>
     </ul>
        {% else %}
      <ul class="navbar-nav">
          <li class="nav-item"><a href="{% url 'users:login' %}" class=" btn-sm btn-primary mr-2 pr-4 pl-4 nav-link text-white">Login</a></li> 
          <li class="nav-item"><a href="{% url 'users:signup' %}" class="btn-sm btn-primary mr-2 pr-4 pl-4 nav-link text-white ">SIGN UP</a></li>
      </ul>
      {% endif %}
    </div>
  </nav>
  
<script type="text/javascript">
  $(document).ready(function() {
    function check_activities() {
      $.ajax({
        url: "/activities/check/",
        cache: false,
        success: function(data) {
          if (data != 0) {
            $("#check_activities span#activities_count").text(data);
          } else {
            $("span#activities_count").remove();
          }
        },
        complete: function() {
          window.setTimeout(check_activities, 60000);
        }
      });
    }
    check_activities();
  });
</script>

templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center mt-5">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>

<nav aria-label="Page navigation example">
  {% if reports.has_other_pages %}
  <ul class="pagination justify-content-center mt-5">
    {% if reports.has_previous %}
      <li><a href="?page={{ reports.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in reports.paginator.page_range %}
      {% if reports.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if reports.has_next %}
      <li><a href="?page={{ reports.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</nav>