core/urls.py
from django.urls import path

urlpatterns = [

]

juniorsproject/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('posts.urls')),
    path('messages/', include('messenger.urls')),
    path('', include('notifications.urls')),
    path('', include('reports.urls')),
    path('', include('groups.urls')),
    path('comment/', include('comments.urls')),
    path('', include('esearch.urls')),
    path('__debug__/', include(debug_toolbar.urls)),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

messenger/urls.py
from django.urls import path
from . import views

app_name = 'messenger'

urlpatterns = [
    path('check/',views.check,name='check_message'),
    path('send/',views.send,name='send_message'),
    path('u/<username>/',views.messages,name='messages'),
    path('',views.inbox,name='inbox'),
    path('delete/',views.delete,name='delete_message'),
    path('load_new_messages/',views.load_new_messages,name='load_new_messages'),
    path('load_last_twenty_messages/',views.load_last_twenty_messages,name='load_last_twenty_messages'),
]

users/api/urls.py
from django.urls import path
from .views import (ProfileRetrieveAPIView, UserLoginAPIView, UserSignUpAPIView, current_user,)

urlpatterns = [
    path('login/',UserLoginAPIView.as_view(),name='users_login'),
    path('signup/',UserSignUpAPIView.as_view(),name='users_signup'),
    path('current_user/',current_user,name='current_user'),
    path('profile/<username>/',ProfileRetrieveAPIView.as_view(),name='profile_info'),
]

users/urls.py
from django.urls import path, reverse_lazy,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import (Signup, profile,
                   user_show_profile, FollowersPageView, FollowingPageView,
                   follow_user, all_message_requests, send_message_request,
                   accept_message_request, all_friends,UsersPageView,block_spammer
                   )
                   

app_name = 'users'

urlpatterns = [
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', login_required(auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'))), name='password_change'),
    path('password-change/done/', login_required(auth_views.PasswordChangeDoneView.as_view()), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('users:password_reset_complete')) , name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    path('profile/<int:id>', user_show_profile, name='profile_show_user'),
    path('following/', FollowingPageView.as_view(), name='view_all_following'),
    path('followers/', FollowersPageView.as_view(), name='view_all_followers'),
    path('follow_user/<user_id>', follow_user, name='follow_user' ),
    path('send_message_request/<user_id>',send_message_request, name='send_message_request'),
    path('accept_message_request/<user_id>', accept_message_request, name='accept_message_request'),
    path('friends/all/',all_friends, name='all_friends'),
    path('friends/requests/',all_message_requests, name='all_message_requests'),
    path('u/',UsersPageView.as_view(),name='view_all_users'),
    path('u/block_spammer/<user_id>/',block_spammer,name='block_spammer'),
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .managers import CustomUserManager
from django_countries.fields import CountryField
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.utils.text import slugify
import random
import os
from django.conf import settings
from django.utils import timezone

# Create your models here.

User = settings.AUTH_USER_MODEL

class CustomUser(AbstractUser): 
    email =  models.EmailField(_('email_address'), unique=True, name='email')
    username =  models.CharField(_('username'), unique=True, max_length=128)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = CustomUserManager()

    def __str__(self):
        return self.email

GENDER_CHOICES = [
    ('male', 'Male'),
    ('female', 'Female')
]

def user_directory_path(instance, filename):
    all_path = 'user_{0}/{1}'.format(instance.user.id, filename)

    return all_path

class Profile(models.Model):
    user = models.OneToOneField(User,  related_name='profile',  on_delete=models.CASCADE)
    img_profile  = models.ImageField(verbose_name='image profile', upload_to=user_directory_path, null=True, blank=True)
    member_since = models.DateTimeField(default=timezone.now)
    birth_date = models.DateField(verbose_name='Birth date', blank=True, null=True)
    gender = models.CharField(max_length=10,choices=GENDER_CHOICES)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    country = CountryField()
    followers = models.ManyToManyField(User, related_name='following')
    pending_list = models.ManyToManyField(User, related_name='my_pending_list')
    contact_list = models.ManyToManyField(User, related_name='contacters', blank=True)

    def __str__(self):
        return self.user.username
    
    def screen_name(self):
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:  
            return self.user.username

    def get_picture(self):
        default_picture = settings.STATIC_URL + 'img/default_picture.png'
        if self.img_profile:
            return self.img_profile.url
        else:
            return default_picture

    def get_number_of_followers(self):
        if self.followers.count():
            return self.followers.count()
        else:
            return 0

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

def save(self, *args, **kwargs):
    slug = slugify(self.username)
    self.slug = slug
    print(slug)
    super().save(*args, **kwargs)
    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from crispy_forms.helper import FormHelper
from django.conf import settings
from .models import Profile
from django.forms.widgets import ClearableFileInput
from bootstrap_datepicker_plus import DatePickerInput

User = settings.AUTH_USER_MODEL


class CustomClearableFileInput(ClearableFileInput):
    template_name = 'profile/custom_clear_file_input.html'


class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = CustomUser
        fields = ('email', 'username' )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None 

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class UserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username','email')


class ProfileForm(forms.ModelForm):
    # img_profile = forms.ImageField(required=False)
    class Meta:
        model = Profile
        fields = ('img_profile', 'birth_date', 'gender', 'country')
        widgets = {
            'img_profile':CustomClearableFileInput(),
            'birth_date':DatePickerInput(format='%m/%d/%Y')
        }
    
 

users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework.decorators import api_view
from rest_framework.generics import RetrieveAPIView
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.status import (HTTP_200_OK, HTTP_201_CREATED, HTTP_400_BAD_REQUEST,)
from rest_framework.views import APIView
from .serializers import (CurrentUserDetailSerializer, ProfileRetrieveSerializer,UserLoginSerializer, UserSerializerWithToken,)

User = get_user_model()

@api_view(['GET'])
def current_user(request):
    serializer = CurrentUserDetailSerializer(request.user,context={"request":request})
    return Response(serializer.data)

class UserSignUpAPIView(APIView):
    permission_classes = [AllowAny]

    def post(self,request,format=None):
        serializer = UserSerializerWithToken(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=HTTP_201_CREATED)
        return Response(serializer.errors,status=HTTP_400_BAD_REQUEST)

class UserLoginAPIView(APIView):
    permission_classes = [AllowAny]
    serializer_class = UserLoginSerializer

    def post(self,request,*args,**kwargs):
        data = request.data
        serializer = UserLoginSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data,status=HTTP_200_OK)
        return Response(serializer.errors,status=HTTP_400_BAD_REQUEST)

class ProfileRetrieveAPIView(RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = ProfileRetrieveSerializer
    lookup_field = 'username'
    lookup_url_kwarg = 'username'

users/views.py
from .forms import CustomUserCreationForm
from django.views import generic
from django.urls import  reverse_lazy
from .forms import UserEditForm, UserEditForm, ProfileForm
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages 
from django.shortcuts import render, get_object_or_404
import os 
from django.http import  HttpResponseRedirect, HttpResponse
from .models import  CustomUser, Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Post
from comments.models import Comment
from itertools import chain
from groups.models import Group
from notifications.models import Notification
from django.core.paginator import  Paginator
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views.generic import ListView
from django.shortcuts import redirect

# Create your views here.
User = settings.AUTH_USER_MODEL

class Signup(generic.CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('users:login')
    
@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST,request.FILES, instance=request.user.profile )
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'your profile was successfully updated')
        else:
            messages.error(request, 'Please correct that errors in your profile form')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile/profile.html', {
        'user_form':user_form,
        'profile_form':profile_form
    })

def user_show_profile(request, id):
    user_base = CustomUser.objects.filter(id=id)
    user_profile = Profile.objects.filter(user_id=id)
    user = request.user
    user_posts = Post.objects.filter(author=id).order_by('-created')
    user_comments = Comment.objects.filter(commenter=id).order_by('-created')
    user_groups_admin = Group.objects.filter(admins=id).order_by('-created')[:5]
    result_post =  sorted(chain(user_posts,user_comments), key=lambda instance: instance.created, reverse=True)
    print(result_post)
    return render(request, 'show_user_profile.html', {'user_list':user_base, 'user_profile':user_profile,'user_posts':user_posts,'user_comments':user_comments,'user':user,'result_post':result_post,'user_groups_admin':user_groups_admin})

class FollowersPageView(LoginRequiredMixin, generic.ListView):
    model = User
    template_name = 'profile/followers.html'
    context_object_name = 'user_followers'
    
    def get_queryset(self, **kwargs):
        print("this for followers user : {0} ".format(self.request.user.profile.followers.all()))
        return self.request.user.profile.followers.all()



class FollowingPageView(LoginRequiredMixin, generic.ListView):
    model = User
    template_name = 'profile/following.html'
    context_object_name = 'profiles'

    def get_queryset(self, **kwargs):
        # print("this for following user :{0} ".format(self.request.user.following.count))
        # print("this for followers user : {0} ".format(self.request.user.profile.following.count()))
        return self.request.user.following.all()
    

def follow_user(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    if request.user in user.profile.followers.all():
        user.profile.followers.remove(request.user)
        text = 'Follow'
    else:
        user.profile.followers.add(request.user)
        Notification.objects.create(
            Actor=request.user,
            Target=user,
            notif_type='follow'
        )
        text = 'Unfollow'
    return HttpResponse(text)
    

@login_required
def send_message_request(request, user_id):
    receiver = get_object_or_404(CustomUser, id=user_id)
    contacter = request.user 

    if contacter in receiver.profile.pending_list.all():
        receiver.profile.pending_list.remove(contacter)
        text = 'Send Request'
    else:
        receiver.profile.pending_list.add(contacter)
        Notification.objects.create(Actor=contacter, Target=receiver, notif_type='sent_msg_request')
        text = 'Request Sent'
    return HttpResponse(text)


@login_required
def accept_message_request(request, user_id):
    sender = get_object_or_404(CustomUser, id=user_id)
    acceptor = request.user 

    if sender in acceptor.profile.pending_list.all():
        acceptor.profile.pending_list.remove(sender)
        acceptor.profile.contact_list.add(sender)
        sender.profile.contact_list.add(acceptor)
        Notification.objects.create(Actor=acceptor, Target=sender,  notif_type='confirmed_msg_request')
        text = 'Added to contact list'
    else:
        text = 'Unexpected error!'
    return HttpResponse(text)


@login_required
def all_message_requests(request):
    message_requests = request.user.profile.pending_list.all()
    paginator = Paginator(message_requests, 20)
    page = request.GET.get('page')
    if paginator.num_pages > 1:
        p = True 
    else:
        p = False 
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    
    except  EmptyPage:
        users = paginator.page(paginator.num_pages)
    
    p_obj = users 

    return render(request, 'profile/view_all_message_requests.html',{
        'users':users,
        'page':page,
        'p':p,
        'p_obje':p_obj
    })

        
@login_required
def all_friends(request):
    user_contact_list = request.user.profile.contact_list.all() 
    paginator = Paginator(user_contact_list, 20)
    page = request.GET.get('page')
    if paginator.num_pages > 1:
        p = True
    else:
        p = False
    try:
        users = paginator.page(page)

    except PageNotAnInteger:
        users = paginator.page(1)

    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    p_obj = users

    return render(request, 'profile/view_all_contacts.html', {
        'users':users,
        'page':page,
        'p':p,
        'p_obj':p_obj
    })

@login_required
def block_spammer(request, user_id):
    spammer = get_object_or_404(CustomUser, id=user_id)
    blocker = request.user
    if spammer in blocker.profile.contact_list.all():
        blocker.profile.contact_list.remove(spammer)
        spammer.profile.contact_list.remove(blocker)
        return redirect('users:profile_show_user', username=spammer)
    else:
        return redirect('/')
        
class UsersPageView(ListView):
    model = User
    paginate_by = 20
    template_name = 'view_all_users.html'
    context_object_name = 'users'

    def get_queryset(self, **kwargs):
        return CustomUser.objects.exclude(username=self.request.user.username)

users/templates/profile/custom_clear_file_input.html
<style>
    input[type="file"] {
    display: none;
}
.custom-file-upload {
    margin: 6px;
    border: 1px solid #ccc;
    display: inline-block;
    padding: 6px 12px;
    cursor: pointer;
}
.custom-file-upload:hover{
    background-color: #0069D9;
    color: white;
    transition: 0.4s;

}
</style>
<label for="file-upload" class="custom-file-upload">
    <i class="fas fa-upload"></i> Upload your image profile 
</label>
<input type="{{ widget.type }}" name="{{ widget.name }}"  id="file-upload">

users/templates/profile/followers.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
{% for user_follower in user_followers %}
  <div class="card mb-2" style="border:none; border-bottom:1px solid #dcd7d7;">
    <div class="card-body p-4">

      <div class="text-center" style="float:left; width:10%;">
        {% if user_follower.profile.get_picture %}
        <img src="{{ user_follower.profile.user.profile.get_picture }}" class="rounded" width="50px" height="50px">
        {% endif %}
      </div>

      <div style="float:right; width:90%;">
        <h5 style="font-size:16px;">
          <a href="{% url 'users:profile_show_user' user.id %}"
            class="card-link"
            title="{{ user_follower.profile.user.username }}">{{ user_follower.profile.screen_name }}</a>
          </h5>
        <p class="text-muted">Member since <span title="{{ user_follower.member_since|date:"D d M Y" }} | {{ user_follower.member_since|time:"H:i:s" }}">{{ user_follower.profile.member_since|naturaltime }}</span></p>
      </div>
      
    </div>
  </div>
  {% empty %}
  <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Following Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You don't have any following right now.</p>
    </div>
  </div>
  {% endfor %}
{% endblock content %}

users/templates/profile/profile.html
{% extends 'base.html' %}

{% load bootstrap4 %} 

{% load static %}

{% load crispy_forms_tags %}

{% block title %}Profile{% endblock title %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    <div class="row justify-content-center" >
        {% if messages %}
        {% for message in messages  %}
        <div class="alert {% if message.tags == 'success' %}  alert-success {% else %} alert-danger {% endif %}">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
        <div class="card col-12 m-4 p-0 pb-4 " >
            <div class="card-header text-center"><h5>Profile</h5></div>
            <div class="row">
                <div class="col-5">
                    <div class="card-body">
                        <img class="ml-3" src="{{user.profile.get_picture}}" width="300px" height="300px" class="rounded" alt="">
                        <div class="offset-2 mt-2">{{profile_form.img_profile}}</div>   
                   </div>
                <div class="p-3 m-4">
                    <a  class="btn btn-primary" href="{% url 'users:view_all_followers' %}">
                        Followers <span class="badge badge-light">{{ user.profile.get_number_of_followers }}</span>
                        <span class="sr-only">unread messages</span>
                    </a>
                      <a  class="btn btn-primary" href="{% url 'users:view_all_following' %}">
                        Following <span class="badge badge-light">{{ user.profile.get_number_of_following }}</span>
                        <span class="sr-only">unread messages</span>
                      </a>
                </div>
                </div>
                <div class="col-6">
                    <div class="card-body">
                        {% csrf_token %}
                        {{user_form|crispy}}
                        {{profile_form.birth_date|as_crispy_field}}
                        {{ profile_form.media }}  
                        {{profile_form.gender|as_crispy_field}}
                        {{profile_form.country|as_crispy_field}}
                        <a href="{% url 'users:password_change' %}" class="card-link"><h5>Change password</h5></a>
                    </div>
                    <button type="submit" class="btn btn-primary float-right mb-4" id="btn">Update</button>
                    <div class="text-danger p-2 m-2">
                        {{ profile_form.non_field_errors }}
                        {{ user_form.non_field_errors }}
                        {{profile_form.img_profile.errors}}
                    </div>
                </div>
            </div>
          
        </div>
    </div>
</form>
{% endblock content %}

users/templates/profile/view_all_contacts.html
{% extends "base.html" %}

{% load humanize %}

{% block title %}All Friends{% endblock title %}

{% block content %}
    {% if users %}
    {% for user in users %}
    <div class="card" style="border:none; border-bottom:1px solid #dcd7d7; margin-bottom:5px;">
      <div class="card-body" style="padding:10px;">
    
        <div class="text-center" style="float:left; width:10%;">
          {% if user.profile.get_picture %}
          <img src="{{ user.profile.get_picture }}" class="rounded" width="50px" height="50px">
          {% endif %}
        </div>
    
        <div style="float:right; width:90%;">
          <h5 style="font-size:16px;">
            <a href="{% url 'users:profile_show_user' user.id %}"
               class="card-link"
               title="{{user.username}}">{{ user.profile.screen_name }}</a>
    
            {% ifequal request.user user %}
            {% else %}
              {% if not request.user in user.profile.contact_list.all %}
                {% if request.user in user.profile.pending_list.all %}
                    <a href="{% url 'users:send_message_request' user.id %}"
                       class="btn btn-primary btn-sm"
                       id="send_message_request"
                       style="float:right; margin-right:10px;"
                       title="Request sent to this users">Request Sent</a>
                {% else %}
                    <a href="{% url 'users:send_message_request' user.id %}"
                       class="btn btn-outline-primary btn-sm"
                       id="send_message_request"
                       style="float:right; margin-right:10px;"
                       title="Send request to this user to start conversation">Send Request</a>
                {% endif %}
              {% else %}
                    <!-- Block User Trigger -->
                    <button type="button" class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#blockUserModel" style="float:right; margin-right:10px;">Block</button>
    
                    <!-- Block User Modal -->
                    <div class="modal fade" id="blockUserModel" tabindex="-1" role="dialog" aria-labelledby="Block User" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title">Are you sure?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <h5>Once you block the user, you can not message him again until he accepts your request.</h5><br>
                            <p>If user is being annoying to you, block him right away.</p>
    
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</button>
                            <a href="{% url 'users:block_spammer' user.id %}" class="btn btn-primary btn-sm" id="block_spammer" style="margin-right: 10px;" title="Block this user">Block</a>
                          </div>
                        </div>
                      </div>
                    </div>
    
                    <a href="{% url 'messenger:messages' user.username %}"
                       class="btn btn-outline-primary btn-sm"
                       title="Send message to this user"
                       style="float:right; margin-right:10px;">Message</a>
              {% endif %}
            {% endifequal %}
    
            {% ifequal request.user user %}
            {% else %}
                {% if request.user in user.profile.followers.all %}
                      <a href="{% url 'users:follow_user' user.id %}"
                     class="btn btn-primary btn-sm"
                     id="follow_user"
                     style="float:right; margin-right:10px;">Unfollow</a>
                {% else %}
                    <a href="{% url 'users:follow_user' user.id %}"
                     class="btn btn-outline-primary btn-sm"
                     id="follow_user"
                     style="float:right; margin-right:10px;">Follow</a>
                {% endif %}
            {% endifequal %}
         </h5>
          <p class="text-muted">Member since <span title="{{user.profile.member_since|date:"D d M Y"}} | {{user.profile.member_since|time:"H:i:s"}}">{{user.profile.member_since|naturaltime}}</span></p>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="card p-4 my-4 mx-0">
    <h6 class="text-center">No Contacts Found</h6>
    <div style="margin:0 auto;">
    <p class="text-muted">You don't have any contact right now.</p>
    </div>
    </div>
    {% endif %}
{% endblock content %}

<script type="text/javascript">
    // Send Request
    $(document).ready(function(){
      $("a#send_message_request").on("click", function () {
        {% if not request.user.is_authenticated %}
        window.location.href = "{% url 'users:login' %}";
        {% else %}
        var $add_btn = $(this);
        var $add_url = $(this).attr("href");
        $.ajax({
          url: $add_url,
          type: 'GET',
          success: function (data) {
            $add_btn.text(data);
    
            if ($add_btn.hasClass('btn-outline-primary')) {
              $add_btn.removeClass('btn-outline-primary').addClass('btn-primary');
            }
            else if ($add_btn.hasClass('btn-primary')) {
              $add_btn.removeClass('btn-primary').addClass('btn-outline-primary');
            }
            else {
              console.log('Unexpected error!');
            }
          }
        });
        {% endif %}
        return false;
      });
    });
    </script>
    
    <script type="text/javascript">
    // Follow user
    $(document).ready(function(){
        $("a#follow_user").on("click", function () {
        {% if not request.user.is_authenticated %}
        window.location.href = "{% url 'users:login' %}";
        {% else %}
        var $follow_btn = $(this);
        var $follow_url = $(this).attr("href");
        $.ajax({
          url: $follow_url,
          type: 'GET',
          success: function (data) {
            $follow_btn.text(data);
    
            if ($follow_btn.hasClass('btn-outline-primary')) {
              $follow_btn.removeClass('btn-outline-primary').addClass('btn-primary');
            }
            else if ($follow_btn.hasClass('btn-primary')) {
              $follow_btn.removeClass('btn-primary').addClass('btn-outline-primary');
            }
            else {
              console.log('Unexpected error!');
            }
          }
        });
        {% endif %}
        return false;
      });
    });
    </script>

users/templates/profile/view_all_message_requests.html
{% extends "base.html" %}

{% load humanize %}

{% load groups_tags %}

{% block content %}
{% for user in users %}
<div class="card" style="border:none; border-bottom:1px solid #dcd7d7; margin-bottom:5px;">
  <div class="card-body" style="padding:10px;">

    <div class="text-center" style="float:left; width:10%;">
      {% if user.profile.get_picture %}
      <img src="{{ user.profile.get_picture }}" class="rounded" width="50px" height="50px">
      {% endif %}
    </div>

    <div style="float:right; width:90%;">
      <h5 style="font-size:16px;">
        <a href="{% url 'users:profile_show_user' user.id %}"
           class="card-link"
           title="{{ user.username }}">{{ user.profile.screen_name }}</a>
        <a href="{% url 'users:accept_message_request' user.id %}"
           class="btn btn-outline-primary btn-sm"
           id="accept_message_request"
           style="float:right;"
           title="Confirm to start a conversation with this user">Confirm</a>
      </h5>
      <p>{{ group.description|markdown|truncatewords_html:50 }}</p>
      <p class="text-muted">Member since <span title="{{user.profile.member_since|date:"D d M Y"}} | {{user.profile.member_since|time:"H:i:s"}}">{{user.profile.member_since|naturaltime}}</span></p>
    </div>
  </div>
</div>
{% empty %}
<div class="card p-4 my-4 mx-0">
  <h6 class="text-center">No Requests Found</h6>
  <div style="margin:0 auto;">
  <p class="text-muted">You don't have any message requests received.</p>
  </div>
</div>
{% endfor %}


<script type="text/javascript">
  $(document).ready(function(){
    $("a#accept_message_request").on("click", function () {
      {% if not request.user.is_authenticated %}
      window.location.href = "{% url 'users:login' %}";
      {% else %}
      var $confirm_btn = $(this);
      var $confirm_url = $(this).attr("href");
      $.ajax({
        url: $confirm_url,
        type: 'GET',
        success: function (data) {
          $confirm_btn.text(data);
  
          if ($confirm_btn.hasClass('btn-outline-primary')) {
            $confirm_btn.removeClass('btn-outline-primary').addClass('btn-primary disabled');
          }
          else {
            console.log('Unexpected error!');
          }
        }
      });
      {% endif %}
      return false;
    });
  });
  </script>
  

{% endblock content %}